title = "Peter Wan Personal Website"
baseURL = "https://peterwan-portfolio.netlify.app/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "This is Peter Wan's Portfolio Website."
  facebook = "https://www.facebook.com/peter.wan.3110/"
  instagram = "https://www.instagram.com/ppeter_wan/"
  github = "https://github.com/ppeterwan"
  linkedin = "https://www.linkedin.com/in/peter-wan/"

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/nyc.jpg"
  recent_posts_number = 2
